### ISSUE TITLE
我试过好几个都是翻译第一句或者前两句就结束了

### ISSUE THREAD

**Issue by tsunho12** [BlackGlory/subtitle-translate-tmt#3]
error：54003，error_msg=Invalid Access Limit

**Comment by BlackGlory** [comment]
据我所知, 错误码54003是百度翻译API的错误代码, 不是腾讯机器翻译的, 请确认你使用的翻译插件是否正确.

**Comment by BlackGlory** [comment]
以下是百度翻译API的相关文档: https://fanyi-api.baidu.com/api/trans/product/apidoc

> 五、 服务调用
> 
> 1. 通用翻译API是否有配额限制？
> 
> 百度翻译通用API无访问频次限制，服务稳定性SLA高达99.99%。
> 
> 2. 定制化翻译API是否有配额限制？
> 
> 百度翻译定制化API目前处于免费公测期，支持默认配额为5qps，不保障并发。当调用频次超过默认配额时，会返回错误代码为54003的错误信息，您需降低调用频率后重新发起请求。
