### ISSUE TITLE
测试异常，无法翻译

### ISSUE THREAD

**Issue by soundclick** [BlackGlory/subtitle-translate-tmt#8]
potplayer版本号:1.7.21632，也重启了，腾讯的接口用在Tern-Subtitle里正常，前一个安装的百度翻译插件倒是正常，不知道问题在哪？

**Comment by BlackGlory** [comment]
我用1.7.21861是正常的:
![image](https://user-images.githubusercontent.com/1365962/217699694-a52ed0fe-245e-4f10-b210-41b9cf49cb83.png)

有出现什么错误提示吗?

**Comment by soundclick** [comment]
- 换了1.7.21873安装版还是不行，也不显示提示信息。![image](https://user-images.githubusercontent.com/12105972/217710680-524ce46a-5e77-496d-9ccd-6376cf56a102.png)

**Comment by BlackGlory** [comment]
很可能是你的帐户设置填错了, 只有在这种情况下会弹出空白.

**Comment by soundclick** [comment]
Bingo，一针见血！thx！
之前用了Ditto，可能鼠标点击复制错了，这回老老实实ctrl + v，正常了。
